$ANSIBLE_VAULT;1.1;AES256
33383632323235303063303064393863383362336430383163366631623063636239623538613966
3438636665356136313635373730346235346337623264310a303465393237313966613562316461
38396262356138363639306339333630316538343062663362356135323163623333613134623966
3931626533623033650a396232666337656635316664363132336632613435313834356237613234
39636430336533646638313630323934306434646234376334636531643665373132326562333161
62663236316464616433323363343631323461643861626638663537613035333664343637333832
623962316331386163643562343939613164
