---
# handlers file for main
- name: restart systemd networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: apply netplan
  ansible.builtin.shell:
    command: netplan apply
  become: true

- name: restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
