---
- name: setup ad
  hosts: domain_controller
  vars_files:
    - ./roles/win/vars/pass.yml
    - ./roles/win/vars/users.yml
  roles:
    - win

- name: join linux to ad
  hosts: linux
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - ./roles/win/vars/pass.yml
    - ./roles/win/vars/main.yml
  roles:
    - linux
